packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  react: ^18.3.1
  react-dom: ^18.3.1
  '@types/react': ^18.3.3
  typescript: ^5.5.3
  eslint: ^8.56.0
  vite: ^5.3.1
  vitest: ^1.6.0
  '@types/bun': ^1.1.8
  jsdom: ^24.1.1
